/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testes;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

import Thermium.DAO.SubstanciaDAO;
import Thermium.ENTITY.Substancia;
import java.util.Vector;

/**
 *
 * @author rosiv
 */
public class NewJInternalFrame1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame1
     */
    public NewJInternalFrame1() {
        initComponents();
        
        textfield = (JTextField)     jComboBox1.getEditor().getEditorComponent();
	    textfield.addKeyListener(new KeyAdapter() {
	    	public void keyReleased(KeyEvent ke) {
	    		SwingUtilities.invokeLater(new Runnable() {
	    			public void run() {
	    				comboFilter(textfield.getText());
	    			}
	    		});
	    	}
		});
            
  
    }
    
    private Object[] getSubstanciasString() {
    	List<String> substanciasStr= new ArrayList<String>();


	    List<Substancia> substancias = sDao.getList();
	    
	    for(Substancia s : substancias) {
	    	substanciasStr.add(s.getNome());
	    }
	    return substanciasStr.toArray();
    }
    
     @SuppressWarnings({ "unchecked", "rawtypes" })
	private void comboFilter(String enteredText) {
	    List<String> filterArray= new ArrayList<String>();


	    List<Substancia> substancias = sDao.pesquisarNomeFragmentoInicio(enteredText);
	    
	    for(Substancia s : substancias) {
	    	filterArray.add(s.getNome());
	    }
	    
	    if (filterArray.size() > 0) {
	        jComboBox1.setModel(new DefaultComboBoxModel(filterArray.toArray()));
	        jComboBox1.setSelectedItem(enteredText);
	        jComboBox1.showPopup();
	    }
	    else {
	        jComboBox1.hidePopup();
	    }
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({ "unchecked", "rawtypes" })
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        jComboBox1.setEditable(true);

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(262, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(98, 98, 98))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        jComboBox1.setModel(new DefaultComboBoxModel(sDao.getList().toArray()));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private SubstanciaDAO sDao = new SubstanciaDAO();	
    private JTextField textfield;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
